"""Build a deterministic, network-free snapshot of the seed-42 demo."""

from __future__ import annotations

from datetime import datetime
import json
from pathlib import Path
import shutil
import tempfile

from core.demo import SAMPLE_DATE, SAMPLE_TIMEZONE, seed_sample
from core.panel import overview_payload, render_board, render_overview, render_thread, task_payload
from core.protocol.task import ProtocolError


SEED = 42
MARKER = ".retinue-static-demo"


def _static_board(body: bytes, tasks: list[dict]) -> bytes:
    text = body.decode()
    text = text.replace("href='/'", "href='index.html'")
    text = text.replace("href='/overview'", "href='overview.html'")
    text = text.replace("href='/?ready=1'", "href='ready.html'")
    for task in tasks:
        text = text.replace(
            f"href='/tasks/{task['id']}'",
            f"href='tasks/{task['id']}.html'",
        )
    return text.encode()


def _static_overview(body: bytes) -> bytes:
    return (
        body.decode()
        .replace("href='/'", "href='index.html'")
        .replace("href='/overview'", "href='overview.html'")
        .encode()
    )


def _static_thread(body: bytes) -> bytes:
    return body.decode().replace("href='/'", "href='../index.html'").encode()


def _render(destination: Path) -> list[str]:
    workspace = destination / "workspace"
    site = destination / "site"
    seed_sample(workspace, seed=SEED)
    tasks = task_payload(workspace)
    now = datetime(
        SAMPLE_DATE.year,
        SAMPLE_DATE.month,
        SAMPLE_DATE.day,
        9,
        15,
        tzinfo=SAMPLE_TIMEZONE,
    )

    (site / "tasks").mkdir(parents=True)
    (site / MARKER).write_text("generated by scripts/build_static_demo.py\n", encoding="utf-8")
    (site / "index.html").write_bytes(_static_board(render_board(tasks), tasks))
    (site / "ready.html").write_bytes(
        _static_board(render_board(tasks, ready_only=True), tasks)
    )
    (site / "overview.html").write_bytes(
        _static_overview(render_overview(overview_payload(workspace, now=now)))
    )
    for task in tasks:
        (site / "tasks" / f"{task['id']}.html").write_bytes(
            _static_thread(render_thread(task))
        )

    pages = [
        "index.html",
        "ready.html",
        "overview.html",
        *(f"tasks/{task['id']}.html" for task in tasks),
    ]
    (site / "build.json").write_text(
        json.dumps(
            {
                "generator": "retinue-static-demo",
                "seed": SEED,
                "network_required": False,
                "pages": pages,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return pages


def build_static_demo(destination: Path | str) -> list[Path]:
    """Build the static site, replacing only a previous marked build."""
    destination = Path(destination).resolve()
    if destination.exists() and any(destination.iterdir()):
        if not (destination / MARKER).is_file():
            raise ProtocolError(
                f"refusing to replace non-generated static demo directory: {destination}"
            )
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(
        prefix="retinue-static-demo-", dir=destination.parent
    ) as temporary:
        temporary_root = Path(temporary)
        pages = _render(temporary_root)
        site = temporary_root / "site"
        if destination.exists():
            shutil.rmtree(destination)
        shutil.copytree(site, destination)
    return [destination / page for page in pages]
