#!/usr/bin/env python3
"""Preserve license texts from the installed production frontend dependency tree.

Run npm ci in webui first. This reads package metadata and LICENSE files only,
never third-party implementation source. Output contains no host paths and is
deterministic for a fixed package-lock/install. Runtime backends retain their
separate inventory in docs/licenses-inventory.md.
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEBUI = ROOT / 'webui'
OUT = ROOT / 'docs' / 'THIRD_PARTY_NOTICES.md'


def production_packages(tree: dict) -> list[tuple[str, str]]:
    found: dict[str, str] = {}

    def walk(dependencies: dict) -> None:
        for name, item in sorted(dependencies.items()):
            if not isinstance(item, dict) or not item.get('version'):
                raise ValueError('production dependency lacks resolved version')
            version = str(item['version'])
            if name in found and found[name] != version:
                raise ValueError('multiple installed versions require explicit path resolution')
            found[name] = version
            walk(item.get('dependencies') or {})

    walk(tree.get('dependencies') or {})
    return sorted(found.items())


def build_notices() -> tuple[str, int]:
    npm = 'npm.cmd' if os.name == 'nt' else 'npm'
    tree = json.loads(subprocess.check_output(
        [npm, 'ls', '--omit=dev', '--all', '--json'], cwd=WEBUI, text=True,
        encoding='utf-8',
    ))
    packages = production_packages(tree)
    lines = [
        '# Third-party notices', '',
        'The public frontend and its offline demo are built with the production',
        'packages listed below. Their original copyright and permission texts are',
        'reproduced from each installed package’s `LICENSE` file. These third-party',
        'licenses remain in force; the MIT license for RETINUE’s own source does',
        'not relicense them.', '',
        'Generated by `python scripts/generate_third_party_notices.py` after',
        '`npm ci` in `webui`. Package versions come from the actual installed',
        '`npm ls --omit=dev --all` tree. No dependency implementation source is',
        'copied into this document. Backend dependencies are listed separately in',
        '[the dependency license inventory](licenses-inventory.md).', '',
    ]
    for name, version in packages:
        package_dir = WEBUI / 'node_modules' / name
        metadata = json.loads((package_dir / 'package.json').read_text(encoding='utf-8'))
        if metadata.get('name') != name or metadata.get('version') != version:
            raise ValueError('installed package does not match resolved dependency tree')
        license_path = package_dir / 'LICENSE'
        if not license_path.is_file():
            raise ValueError(f'{name}: LICENSE file missing; review before shipping')
        original = license_path.read_bytes()
        body = original.decode('utf-8').replace('\r\n', '\n')
        lines.extend([
            f'## {name} {version}', '',
            f'Package license metadata: `{metadata.get("license", "unspecified")}`.',
            f'Original LICENSE SHA-256: `{hashlib.sha256(original).hexdigest()}`.', '',
            '```text', body.rstrip('\n'), '```', '',
        ])
    return '\n'.join(lines).rstrip('\n') + '\n', len(packages)


def main() -> int:
    body, count = build_notices()
    OUT.write_text(body, encoding='utf-8', newline='')
    print(json.dumps({'production_packages': count, 'notice_bytes': len(body.encode('utf-8'))}))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
